### ISSUE TITLE
These jobs were not ready=['maas-import-resources']

### ISSUE THREAD

**Issue by nagajagan** [airshipit/treasuremap#33]
This issue is on Airship v1.7 ( environment is behind proxy server)

`wget http://images.maas.io/ephemeral-v3/daily/streams/v1/index.sjson` is successful from genesis node but still I am facing this issue.

Here is the error log from bootstrap-armada.log
```
2020-09-09 00:23:34.587 384 ERROR armada.handlers.armada [-] Chart deploy [ucp-maas] failed: armada.exceptions.k8s_exceptions.KubernetesWatchTimeoutException: Timed out waiting for jobs (namespace=ucp, labels=(release_group=airship-maas)). These jobs were not ready=['maas-import-resources']
2020-09-09 00:23:34.587 384 ERROR armada.handlers.armada Traceback (most recent call last):
2020-09-09 00:23:34.587 384 ERROR armada.handlers.armada   File "/usr/local/lib/python3.5/dist-packages/armada/handlers/armada.py", line 235, in handle_result
2020-09-09 00:23:34.587 384 ERROR armada.handlers.armada     result = get_result()
2020-09-09 00:23:34.587 384 ERROR armada.handlers.armada   File "/usr/lib/python3.5/concurrent/futures/_base.py", line 398, in result
2020-09-09 00:23:34.587 384 ERROR armada.handlers.armada     return self.__get_result()
2020-09-09 00:23:34.587 384 ERROR armada.handlers.armada   File "/usr/lib/python3.5/concurrent/futures/_base.py", line 357, in __get_result
2020-09-09 00:23:34.587 384 ERROR armada.handlers.armada     raise self._exception
2020-09-09 00:23:34.587 384 ERROR armada.handlers.armada   File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
2020-09-09 00:23:34.587 384 ERROR armada.handlers.armada     result = self.fn(*self.args, **self.kwargs)
2020-09-09 00:23:34.587 384 ERROR armada.handlers.armada   File "/usr/local/lib/python3.5/dist-packages/armada/handlers/armada.py", line 224, in deploy_chart
2020-09-09 00:23:34.587 384 ERROR armada.handlers.armada     concurrency)
2020-09-09 00:23:34.587 384 ERROR armada.handlers.armada   File "/usr/local/lib/python3.5/dist-packages/armada/handlers/chart_deploy.py", line 54, in execute
2020-09-09 00:23:34.587 384 ERROR armada.handlers.armada     ch, cg_test_all_charts, prefix, known_releases)
2020-09-09 00:23:34.587 384 ERROR armada.handlers.armada   File "/usr/local/lib/python3.5/dist-packages/armada/handlers/chart_deploy.py", line 278, in _execute
2020-09-09 00:23:34.587 384 ERROR armada.handlers.armada     chart_wait.wait(timer)
2020-09-09 00:23:34.587 384 ERROR armada.handlers.armada   File "/usr/local/lib/python3.5/dist-packages/armada/handlers/wait.py", line 134, in wait
2020-09-09 00:23:34.587 384 ERROR armada.handlers.armada     wait.wait(timeout=timeout)
2020-09-09 00:23:34.587 384 ERROR armada.handlers.armada   File "/usr/local/lib/python3.5/dist-packages/armada/handlers/wait.py", line 294, in wait
2020-09-09 00:23:34.587 384 ERROR armada.handlers.armada     modified = self._wait(deadline)
2020-09-09 00:23:34.587 384 ERROR armada.handlers.armada   File "/usr/local/lib/python3.5/dist-packages/armada/handlers/wait.py", line 354, in _wait
2020-09-09 00:23:34.587 384 ERROR armada.handlers.armada     raise k8s_exceptions.KubernetesWatchTimeoutException(error)
2020-09-09 00:23:34.587 384 ERROR armada.handlers.armada armada.exceptions.k8s_exceptions.KubernetesWatchTimeoutException: Timed out waiting for jobs (namespace=ucp, labels=(release_group=airship-maas)). These jobs were not ready=['maas-import-resources']
2020-09-09 00:23:34.587 384 ERROR armada.handlers.armada ^[[00m
2020-09-09 00:23:34.588 384 ERROR armada.handlers.armada [-] Chart deploy(s) failed: ['ucp-maas']^[[00m

```
These are the Errors on MAAS GUI.
![maas-import-resources](https://user-images.githubusercontent.com/11877480/92543664-aed85380-f211-11ea-8672-d8422e8491e9.PNG)

**Comment by nagajagan** [comment]
Didn't face this issues when the ENV  got direct internet connection. We see this issue  only when  ENV is behind the Proxy Server.
