### ISSUE TITLE
horizon pods are not coming up

### ISSUE THREAD

**Issue by nagajagan** [airshipit/treasuremap#36]
Seems like latest horizon image is broken, please provide me a work around or correct me if I am wrong. 

```
$ kubectl get pods --all-namespaces | grep Running |  grep 0/
openstack     horizon-bb4cdc644-8v7tp                                         0/1     Running     11         72m
openstack     horizon-bb4cdc644-cpqdz                                         0/1     Running     11         72m

$ kubectl -n openstack logs horizon-bb4cdc644-cpqdz
....
10.123.42.12 - - [11/Sep/2020:01:20:26 +0000] "GET / HTTP/1.1" 500 531
10.123.42.12 - - [11/Sep/2020:01:20:26 +0000] "GET / HTTP/1.1" 500 531 "-" "kube-probe/1.12"
2020-09-11 01:20:36.620622 mod_wsgi (pid=110): Exception occurred processing WSGI script '/var/www/cgi-bin/horizon/django.wsgi'.
2020-09-11 01:20:36.620644 Traceback (most recent call last):
2020-09-11 01:20:36.620658   File "/var/lib/openstack/lib/python2.7/site-packages/django/core/handlers/wsgi.py", line 170, in __call__
2020-09-11 01:20:36.620680     self.load_middleware()
2020-09-11 01:20:36.620684   File "/var/lib/openstack/lib/python2.7/site-packages/django/core/handlers/base.py", line 52, in load_middleware
2020-09-11 01:20:36.620693     mw_instance = mw_class()
2020-09-11 01:20:36.620696   File "/var/lib/openstack/lib/python2.7/site-packages/django/middleware/locale.py", line 24, in __init__
2020-09-11 01:20:36.620706     for url_pattern in get_resolver(None).url_patterns:
2020-09-11 01:20:36.620709   File "/var/lib/openstack/lib/python2.7/site-packages/django/core/urlresolvers.py", line 401, in url_patterns
2020-09-11 01:20:36.620719     patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
2020-09-11 01:20:36.620722   File "/var/lib/openstack/lib/python2.7/site-packages/django/core/urlresolvers.py", line 395, in urlconf_module
2020-09-11 01:20:36.620729     self._urlconf_module = import_module(self.urlconf_name)
2020-09-11 01:20:36.620735   File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
2020-09-11 01:20:36.620746     __import__(name)
2020-09-11 01:20:36.620750   File "/var/lib/openstack/lib/python2.7/site-packages/openstack_dashboard/urls.py", line 41, in <module>
2020-09-11 01:20:36.620758     url(r'', include(horizon.urls)),
2020-09-11 01:20:36.620762   File "/var/lib/openstack/lib/python2.7/site-packages/django/conf/urls/__init__.py", line 34, in include
2020-09-11 01:20:36.620771     patterns = getattr(urlconf_module, 'urlpatterns', urlconf_module)
2020-09-11 01:20:36.620784   File "/var/lib/openstack/lib/python2.7/site-packages/django/utils/functional.py", line 225, in inner
2020-09-11 01:20:36.620793     self._setup()
2020-09-11 01:20:36.620797   File "/var/lib/openstack/lib/python2.7/site-packages/django/utils/functional.py", line 376, in _setup
2020-09-11 01:20:36.620805     self._wrapped = self._setupfunc()
2020-09-11 01:20:36.620809   File "/var/lib/openstack/lib/python2.7/site-packages/horizon/base.py", line 832, in url_patterns
2020-09-11 01:20:36.620818     return self._urls()[0]
2020-09-11 01:20:36.620822   File "/var/lib/openstack/lib/python2.7/site-packages/horizon/base.py", line 866, in _urls
2020-09-11 01:20:36.620829     include(dash._decorated_urls)))
2020-09-11 01:20:36.620833   File "/var/lib/openstack/lib/python2.7/site-packages/horizon/base.py", line 543, in _decorated_urls
2020-09-11 01:20:36.620840     include(panel._decorated_urls)))
2020-09-11 01:20:36.620844   File "/var/lib/openstack/lib/python2.7/site-packages/horizon/base.py", line 317, in _decorated_urls
2020-09-11 01:20:36.620851     urlpatterns = self._get_default_urlpatterns()
2020-09-11 01:20:36.620854   File "/var/lib/openstack/lib/python2.7/site-packages/horizon/base.py", line 120, in _get_default_urlpatterns
2020-09-11 01:20:36.620861     urls_mod = import_module('.urls', package_string)
2020-09-11 01:20:36.620865   File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
2020-09-11 01:20:36.620871     __import__(name)
2020-09-11 01:20:36.620875   File "/var/lib/openstack/lib/python2.7/site-packages/heat_dashboard/content/stacks/urls.py", line 15, in <module>
2020-09-11 01:20:36.620883     from heat_dashboard.content.stacks import views
2020-09-11 01:20:36.620887   File "/var/lib/openstack/lib/python2.7/site-packages/heat_dashboard/content/stacks/views.py", line 19, in <module>
2020-09-11 01:20:36.620894     from django.urls import reverse
2020-09-11 01:20:36.620905 ImportError: No module named urls
10.123.42.12 - - [11/Sep/2020:01:20:36 +0000] "GET / HTTP/1.1" 500 531
10.123.42.12 - - [11/Sep/2020:01:20:36 +0000] "GET / HTTP/1.1" 500 531 "-" "kube-probe/1.12"

$ kubectl -n openstack describe pod horizon-bb4cdc644-cpqdz | grep Image
    Image:         quay.io/airshipit/kubernetes-entrypoint:v1.0.0
    Image ID:      docker-pullable://quay.io/airshipit/kubernetes-entrypoint@sha256:038a41765607d40faa5e3864a513efa28a874c7af81829e323418948ebe0857f
    Image:         docker.io/openstackhelm/horizon:ocata-ubuntu_xenial
    Image ID:      docker-pullable://openstackhelm/horizon@sha256:c6f3212936207a699de4ac59ad1e125f9e76d46d553a4bd1e4d2b3d5fa45508a

$ docker images | grep horizon
openstackhelm/horizon                                                ocata-ubuntu_xenial                                      b86d9778684d        3 weeks ago         387MB
```

**Comment by imarijitbose** [comment]
Naga, As discussed please override the horizon image in version.yaml with : docker.io/openstackhelm/horizon:ocata-ubuntu_xenial-20200513

Working to get the latest image fixed and pushed very soon.

**Comment by nagajagan** [comment]
Thank you @imarijitbose your  suggestion worked for me.
